version: '3.9'

services:
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
      - ./repository/db/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "randomasspass"

  app:
    build: .
    image: cfo
    depends_on:
      - db
    ports:
      - "6002:6002"
    env_file:
      - .env

volumes:
  db:
