version: '3.9'

services:
  db:
    image: postgres:alpine
    container_name: lapo-register
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./repository/db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "randomasspass"

  app:
    build: .
    image: cfo
    container_name: samu-alajo
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "6001:6001"
    env_file:
      - .env

volumes:
  db:
